// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patient_Registration_System.Views;

#nullable disable

namespace Patient_Registration_System.Migrations.BillSurg
{
    [DbContext(typeof(BillSurgContext))]
    partial class BillSurgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Patient_Registration_System.Views.BillSurg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdditionalCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("LabTests")
                        .HasColumnType("REAL");

                    b.Property<double>("MedicationCost")
                        .HasColumnType("REAL");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ServiceCharges")
                        .HasColumnType("REAL");

                    b.Property<double>("SurgCharge")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Billsurgs");
                });
#pragma warning restore 612, 618
        }
    }
}
